### ISSUE TITLE
Sonsuz Yol Oyunu

### ISSUE THREAD

**Issue by furkanevrenguzel** [gokberkh/endlessRoad#1]

**Comment by gokberkh** [comment]
Merhabalar , sürümden dolayı olmuş kırmızı altınları ekledim. Araç rengini ve zemini düzelttim.

İyi çalışmalar diliyorum.

**Comment by evrenguzel** [comment]
Teşekkür ederim Gökberk Bey. Ayrıca Android’de nasıl kullanabilirim? Yükleme yolunu kısaca bahseder misiniz? Oyununuzu beğendim, oynamakta isterim. 

Saygılarımla.

**Comment by evrenguzel** [comment]
Oyun alanında yalnızca evler ve ağaçlar var başka alan yok. Direksiyon gibi tuşlarda game ekranında gözükmemekte. Bilginize efendim.

**Comment by evrenguzel** [comment]
Kusura bakmayın yoğunsunuz biliyorum ancak umarım müsait olduğunuzda incelersiniz.
